name: my first workflow
on: push

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "Hello world"

      - name: list files
        run: ls 

      - name: read files
        run: |
        sudo apt-get update
        sudo apt-get install -y git
        git clone git@github.com:apu-wtag/github_actions_testing_basic.git
        cd github_actions_testing_basic
        cat README.md
