name: my first workflow
on: push

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: List and Read files
        run: |
         echo "Hello world"
         echo "listing files"
         ls -la
         echo "cating readme"
         cat README.md
      
      - name: generate ascii artwork
        run: |
         sudo apt update
         sudo apt install cowsay
         cowsay -f dragon "Runn for cover, I am a dragon....RAWR" >> dragon.txt

