name: generate_ascii
on: push
jobs: 
  generate_ascii: 
   runs-on: ubuntu-latest
   steps: 
     - name: checkout code
       uses: actions/checkout@v4

     - name: cowsay program via shell script
       run: |
        chmod +x ascii_script.sh
        ./ascii_script.sh

     - name: checkout repo files
       run: ls -la