name: generate_ascii
on: push
jobs: 
  build_job: 
   runs-on: ubuntu-latest
   steps: 
     - name: install cowsay program
       run: sudo apt-get install cowsay -y
     
     - name: execute cowsay cmd
       run: cowsay -f dragon "Run for cover, I am a dragon ... RWAR" >> dragon.txt
    
     - name: sleep for 30 sec
       run: sleep 30
  
  test_job:
   needs: build_job
   runs-on: ubuntu-latest
   steps: 
     - name: sleep for 10 sec
       run: sleep 10
     
     - name: test file exists
       run: grep -i "dragon" dragon.txt
  
  deploy_job:
   needs: test_job
   runs-on: ubuntu-latest
   steps: 
     - name: sleep for 20 sec
       run: sleep 20
     
     - name: read file
       run: cat dragon.txt
    
     - name: deploying..
       run: echo "deploying......"
