name: Matrix Configuration

on:
  push:

jobs:
    deploy:
      strategy:
        matrix: 
          os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image ${{ matrix.images }}
        run: docker run ${{ matrix.images }}