name: Matrix Configuration

on:
  push:

jobs:
    deploy:
      strategy:
        max-parallel: 8
        matrix: 
          os: [ubuntu-latest, ubuntu-22.04, windows-latest]
          images: [hello-world, alpine]
          exclude:
            - images: alpine
              os: windows-latest
          include:
            - images: amd64/alpine
              os: ubuntu-latest
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image ${{ matrix.images }}
        run: docker run ${{ matrix.images }}